/**
 * Reads registry/registry.ts + the files on disk and emits:
 *   public/r/<name>.json                 shadcn registry item (files inlined) for the CLI
 *   public/r/registry.json               index of all items
 *   registry/__sources__.generated.ts    iframe sources, usage snippets, single-file "manual"
 *                                         code (React + HTML), and the @theme tokens block
 *
 * Run with: pnpm registry:build
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { codeToHtml } from 'shiki';
import { registry } from '../registry/index';

const here = dirname(fileURLToPath(import.meta.url));
const appRoot = resolve(here, '..'); // apps/docs
const publicR = join(appRoot, 'public', 'r');

const read = (rel: string) => readFile(join(appRoot, rel), 'utf8');

type Lang = 'tsx' | 'ts' | 'html' | 'js' | 'css';

const highlight = (code: string, lang: Lang) =>
  codeToHtml(code, { lang, theme: 'github-dark', colorReplacements: { '#24292e': 'transparent' } });

const snippet = async (code: string, lang: Lang) => ({
  code,
  codeHtml: await highlight(code, lang),
});

/** Map a registry file to a shadcn registry-item file type. */
function shadcnFileType(path: string, kind: 'react' | 'html' | 'script') {
  if (kind !== 'react') return 'registry:file';
  if (/(^|\/)use-[^/]+\.ts$/.test(path) || path.includes('/hooks/')) return 'registry:hook';
  return 'registry:component';
}

async function main() {
  await mkdir(publicR, { recursive: true });

  const index: Array<Record<string, unknown>> = [];
  const sources: Record<string, { html: string }> = {};
  const scripts: Record<string, string> = {};
  const cssTokens: Record<string, { code: string; codeHtml: string }> = {};
  const usage: Record<string, { react: unknown; html: unknown }> = {};
  const manual: Record<string, { react: unknown; html: unknown }> = {};

  for (const entry of registry) {
    const shadcnFiles = [];
    let reactCode = '';
    let htmlMarkup = '';
    let jsCode = '';

    for (const f of entry.files) {
      const content = await read(f.path);
      shadcnFiles.push({
        path: f.target,
        type: shadcnFileType(f.path, f.kind),
        target: f.target,
        content,
      });
      if (f.kind === 'react') reactCode ||= content;
      if (f.kind === 'html') htmlMarkup ||= content;
      if (f.kind === 'script') {
        jsCode = content;
        scripts[entry.name] = content;
      }
    }

    // Single-file "manual" copy: React file as-is; HTML = markup + inline <script>.
    const htmlSingle = `${htmlMarkup.trimEnd()}\n\n<script>\n${jsCode.trimEnd()}\n</script>\n`;
    manual[entry.name] = {
      react: await snippet(reactCode, 'tsx'),
      html: await snippet(htmlSingle, 'html'),
    };

    usage[entry.name] = {
      react: await snippet(entry.usage.react, 'tsx'),
      html: await snippet(entry.usage.html, 'html'),
    };

    if (Object.keys(entry.cssVars).length > 0) {
      const cssCode = `@theme {\n${Object.entries(entry.cssVars)
        .map(([k, v]) => `  ${k}: ${v};`)
        .join('\n')}\n}`;
      cssTokens[entry.name] = { code: cssCode, codeHtml: await highlight(cssCode, 'css') };
    }

    const item = {
      $schema: 'https://ui.shadcn.com/schema/registry-item.json',
      name: entry.name,
      type: entry.type === 'block' ? 'registry:block' : 'registry:ui',
      title: entry.title,
      description: entry.description,
      dependencies: entry.dependencies,
      registryDependencies: entry.registryDependencies,
      cssVars: {
        theme: Object.fromEntries(
          Object.entries(entry.cssVars).map(([k, v]) => [k.replace(/^--/, ''), v])
        ),
      },
      files: shadcnFiles,
    };

    await writeFile(join(publicR, `${entry.name}.json`), JSON.stringify(item, null, 2));
    index.push({
      name: entry.name,
      type: entry.type,
      title: entry.title,
      description: entry.description,
    });

    for (const v of entry.variants) {
      sources[`${entry.name}:${v.id}`] = { html: await read(v.htmlSource) };
    }
  }

  await writeFile(
    join(publicR, 'registry.json'),
    JSON.stringify({ name: 'tween-ui', homepage: 'https://tweenui.dev', items: index }, null, 2)
  );

  const generated =
    `// AUTO-GENERATED by scripts/build-registry.ts — do not edit by hand.\n` +
    `export interface Snippet {\n  code: string;\n  codeHtml: string;\n}\n\n` +
    `export const sources: Record<string, { html: string }> = ${JSON.stringify(sources, null, 2)};\n\n` +
    `export const scripts: Record<string, string> = ${JSON.stringify(scripts, null, 2)};\n\n` +
    `export const cssTokens: Record<string, Snippet> = ${JSON.stringify(cssTokens, null, 2)};\n\n` +
    `export const usage: Record<string, { react: Snippet; html: Snippet }> = ${JSON.stringify(usage, null, 2)};\n\n` +
    `export const manual: Record<string, { react: Snippet; html: Snippet }> = ${JSON.stringify(manual, null, 2)};\n`;
  await writeFile(join(appRoot, 'registry', '__sources__.generated.ts'), generated);

  console.log(`✓ registry built: ${registry.length} item(s)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
