// AUTO-GENERATED by scripts/build-registry.ts — do not edit by hand.
'use client';

import type { ComponentType } from 'react';
import dynamic from 'next/dynamic';

/**
 * Live demo map for <ComponentPreview>. Demos are client-only (hover, focus
 * and timers), so each is loaded through next/dynamic.
 */
export const demos: Record<string, ComponentType> = {
  'icon-trail-button:default': dynamic(() => import('./demos/icon-trail-button')),
  'sliding-tabs:default': dynamic(() => import('./demos/sliding-tabs')),
  'avatar-reveal:default': dynamic(() => import('./demos/avatar-reveal')),
  'auth-modal:default': dynamic(() => import('./demos/auth-modal')),
  'number-counter:instant': dynamic(() => import('./demos/number-counter')),
  'number-counter:viewport': dynamic(() => import('./demos/number-counter-viewport')),
  'voice-sample-player:default': dynamic(() => import('./demos/voice-sample-player')),
  'flip-card:default': dynamic(() => import('./demos/flip-card')),
  'faq-accordion:default': dynamic(() => import('./demos/faq-accordion')),
  'shiny-button:default': dynamic(() => import('./demos/shiny-button')),
  'text-roll-button:default': dynamic(() => import('./demos/text-roll-button')),
  'slide-arrow-button:default': dynamic(() => import('./demos/slide-arrow-button')),
  'glow-button:default': dynamic(() => import('./demos/glow-button')),
  'logo-orbit:default': dynamic(() => import('./demos/logo-orbit')),
  'logo-cycle:default': dynamic(() => import('./demos/logo-cycle')),
  'logo-wave:default': dynamic(() => import('./demos/logo-wave')),
  'image-fan-slider:default': dynamic(() => import('./demos/image-fan-slider')),
  'morphing-text:default': dynamic(() => import('./demos/morphing-text')),
  'pricing-plan-switch:default': dynamic(() => import('./demos/pricing-plan-switch')),
  'process-card-reveal:default': dynamic(() => import('./demos/process-card-reveal')),
  'process-sticky-steps:default': dynamic(() => import('./demos/process-sticky-steps')),
  'strip-wipe:default': dynamic(() => import('./demos/strip-wipe')),
  'rating-carousel:default': dynamic(() => import('./demos/rating-carousel')),
  'cta-image-fan:default': dynamic(() => import('./demos/cta-image-fan')),
  'cta-photo-headline:default': dynamic(() => import('./demos/cta-photo-headline')),
  'blog-hover-expand:default': dynamic(() => import('./demos/blog-hover-expand')),
  'integration-hub:default': dynamic(() => import('./demos/integration-hub')),
  'infinite-rotating-cards:default': dynamic(() => import('./demos/infinite-rotating-cards')),
  'card-hover-expand:default': dynamic(() => import('./demos/card-hover-expand')),
  'card-spotlight-grid:default': dynamic(() => import('./demos/card-spotlight-grid')),
  'column-drift:default': dynamic(() => import('./demos/column-drift')),
  'team-scatter-focus:default': dynamic(() => import('./demos/team-scatter-focus')),
  'tab-wipe:default': dynamic(() => import('./demos/tab-wipe')),
  'logo-wall-shuffle:default': dynamic(() => import('./demos/logo-wall-shuffle')),
  'testimonial-line-sweep:default': dynamic(() => import('./demos/testimonial-line-sweep')),
  'cta-starfall:default': dynamic(() => import('./demos/cta-starfall')),
  'pricing-usage-slider:default': dynamic(() => import('./demos/pricing-usage-slider')),
  'grid-cascade:default': dynamic(() => import('./demos/grid-cascade')),
};

export function getDemo(component: string, variant: string): ComponentType | undefined {
  return demos[`${component}:${variant}`];
}
