// AUTO-GENERATED by scripts/build-registry.ts — do not edit by hand.
'use client';

import type { ComponentType } from 'react';
import dynamic from 'next/dynamic';

/**
 * Live demo map for <ComponentPreview>. Demos are client-only (hover, focus
 * and timers), so each is loaded through next/dynamic.
 */
export const demos: Record<string, ComponentType> = {
  'animated-sliding-button:default': dynamic(() => import('./demos/animated-sliding-button')),
  'sliding-tab-on-hover:default': dynamic(() => import('./demos/sliding-tab-on-hover')),
  'avatar-reveal:default': dynamic(() => import('./demos/avatar-reveal')),
  'auth-modal:default': dynamic(() => import('./demos/auth-modal')),
  'counter-number-on-scroll:instant': dynamic(() => import('./demos/counter-number-on-scroll')),
  'counter-number-on-scroll:viewport': dynamic(() => import('./demos/counter-number-on-scroll-viewport')),
  'voice-sample-player:default': dynamic(() => import('./demos/voice-sample-player')),
  'flip-card-on-hover:default': dynamic(() => import('./demos/flip-card-on-hover')),
  'faq-accordion:default': dynamic(() => import('./demos/faq-accordion')),
  'shiny-button:default': dynamic(() => import('./demos/shiny-button')),
  'text-roll-button:default': dynamic(() => import('./demos/text-roll-button')),
  'slide-arrow-button:default': dynamic(() => import('./demos/slide-arrow-button')),
  'glow-button:default': dynamic(() => import('./demos/glow-button')),
  'logo-orbit:default': dynamic(() => import('./demos/logo-orbit')),
  'logo-cycle:default': dynamic(() => import('./demos/logo-cycle')),
  'logo-wave:default': dynamic(() => import('./demos/logo-wave')),
  'image-fan-slider:default': dynamic(() => import('./demos/image-fan-slider')),
  'pricing-plan-switch:default': dynamic(() => import('./demos/pricing-plan-switch')),
  'process-card-reveal:default': dynamic(() => import('./demos/process-card-reveal')),
  'process-sticky-steps:default': dynamic(() => import('./demos/process-sticky-steps')),
  'testimonial-split-slide:default': dynamic(() => import('./demos/testimonial-split-slide')),
  'testimonial-card-carousel:default': dynamic(() => import('./demos/testimonial-card-carousel')),
  'cta-image-fan:default': dynamic(() => import('./demos/cta-image-fan')),
  'cta-headline-photos:default': dynamic(() => import('./demos/cta-headline-photos')),
  'blog-hover-expand:default': dynamic(() => import('./demos/blog-hover-expand')),
  'integration-hub:default': dynamic(() => import('./demos/integration-hub')),
  'hero-rotating-cards:default': dynamic(() => import('./demos/hero-rotating-cards')),
  'scroll-spin-image:default': dynamic(() => import('./demos/scroll-spin-image')),
  'card-expand-on-hover:default': dynamic(() => import('./demos/card-expand-on-hover')),
};

export function getDemo(component: string, variant: string): ComponentType | undefined {
  return demos[`${component}:${variant}`];
}
