// AUTO-GENERATED by scripts/build-registry.ts — do not edit by hand.
import type { RegistryMedia } from './schema';

/**
 * Preview media found under public/media. Drop a file in, run
 * `pnpm registry:build`, and the gallery card picks it up — an entry's own
 * `media` field still wins if it sets one explicitly.
 */
export const discoveredMedia: Record<string, RegistryMedia> = {
  'icon-trail-button': {
    image: '/media/icon-trail-button-poster.png',
    video: '/media/icon-trail-button-video.webm',
  },
};
