// AUTO-GENERATED by scripts/build-registry.ts — do not edit by hand.
import type { RegistryMedia } from './schema';

/**
 * Preview media found under public/media. Drop a file in, run
 * `pnpm registry:build`, and the gallery card picks it up — an entry's own
 * `media` field still wins if it sets one explicitly.
 */
export const discoveredMedia: Record<string, RegistryMedia> = {
  'icon-trail-button': {"image":"/media/components/icon-trail-button-poster.webp","video":"/media/components/icon-trail-button-preview.mp4"},
  'sliding-tabs': {"image":"/media/components/sliding-tabs-poster.webp","video":"/media/components/sliding-tabs-preview.mp4"},
  'avatar-reveal': {"image":"/media/components/avatar-reveal-poster.webp","video":"/media/components/avatar-reveal-preview.mp4"},
  'auth-modal': {"image":"/media/components/auth-modal-poster.webp","video":"/media/components/auth-modal-preview.mp4"},
  'number-counter': {"image":"/media/components/number-counter-poster.webp","video":"/media/components/number-counter-preview.mp4"},
  'voice-sample-player': {"image":"/media/components/voice-sample-player-poster.webp","video":"/media/components/voice-sample-player-preview.mp4"},
  'flip-card': {"image":"/media/components/flip-card-poster.webp","video":"/media/components/flip-card-preview.mp4"},
  'faq-accordion': {"image":"/media/components/faq-accordion-poster.webp","video":"/media/components/faq-accordion-preview.mp4"},
  'shiny-button': {"image":"/media/components/shiny-button-poster.webp","video":"/media/components/shiny-button-preview.mp4"},
  'text-roll-button': {"image":"/media/components/text-roll-button-poster.webp","video":"/media/components/text-roll-button-preview.mp4"},
  'slide-arrow-button': {"image":"/media/components/slide-arrow-button-poster.webp","video":"/media/components/slide-arrow-button-preview.mp4"},
  'glow-button': {"image":"/media/components/glow-button-poster.webp","video":"/media/components/glow-button-preview.mp4"},
  'logo-orbit': {"image":"/media/components/logo-orbit-poster.webp","video":"/media/components/logo-orbit-preview.mp4"},
  'logo-cycle': {"image":"/media/components/logo-cycle-poster.webp","video":"/media/components/logo-cycle-preview.mp4"},
  'logo-wave': {"image":"/media/components/logo-wave-poster.webp","video":"/media/components/logo-wave-preview.mp4"},
  'image-fan-slider': {"image":"/media/components/image-fan-slider-poster.webp","video":"/media/components/image-fan-slider-preview.mp4"},
  'morphing-text': {"image":"/media/components/morphing-text-poster.webp","video":"/media/components/morphing-text-preview.mp4"},
  'pricing-plan-switch': {"image":"/media/blocks/pricing-plan-switch-poster.webp","video":"/media/blocks/pricing-plan-switch-preview.mp4"},
  'process-card-reveal': {"image":"/media/blocks/process-card-reveal-poster.webp","video":"/media/blocks/process-card-reveal-preview.mp4"},
  'process-sticky-steps': {"image":"/media/blocks/process-sticky-steps-poster.webp","video":"/media/blocks/process-sticky-steps-preview.mp4"},
  'strip-wipe': {"image":"/media/blocks/strip-wipe-poster.webp","video":"/media/blocks/strip-wipe-preview.mp4"},
  'rating-carousel': {"image":"/media/blocks/rating-carousel-poster.webp","video":"/media/blocks/rating-carousel-preview.mp4"},
  'cta-image-fan': {"image":"/media/blocks/cta-image-fan-poster.webp","video":"/media/blocks/cta-image-fan-preview.mp4"},
  'cta-photo-headline': {"image":"/media/blocks/cta-photo-headline-poster.webp","video":"/media/blocks/cta-photo-headline-preview.mp4"},
  'blog-hover-expand': {"image":"/media/blocks/blog-hover-expand-poster.webp","video":"/media/blocks/blog-hover-expand-preview.mp4"},
  'integration-hub': {"image":"/media/blocks/integration-hub-poster.webp","video":"/media/blocks/integration-hub-preview.mp4"},
  'infinite-rotating-cards': {"image":"/media/blocks/infinite-rotating-cards-poster.webp","video":"/media/blocks/infinite-rotating-cards-preview.mp4"},
  'card-hover-expand': {"image":"/media/blocks/card-hover-expand-poster.webp","video":"/media/blocks/card-hover-expand-preview.mp4"},
  'card-spotlight-grid': {"image":"/media/blocks/card-spotlight-grid-poster.webp","video":"/media/blocks/card-spotlight-grid-preview.mp4"},
  'column-drift': {"image":"/media/blocks/column-drift-poster.webp","video":"/media/blocks/column-drift-preview.mp4"},
  'team-scatter-focus': {"image":"/media/blocks/team-scatter-focus-poster.webp","video":"/media/blocks/team-scatter-focus-preview.mp4"},
  'tab-wipe': {"image":"/media/blocks/tab-wipe-poster.webp","video":"/media/blocks/tab-wipe-preview.mp4"},
  'logo-wall-shuffle': {"image":"/media/blocks/logo-wall-shuffle-poster.webp","video":"/media/blocks/logo-wall-shuffle-preview.mp4"},
  'testimonial-line-sweep': {"image":"/media/blocks/testimonial-line-sweep-poster.webp","video":"/media/blocks/testimonial-line-sweep-preview.mp4"},
  'cta-starfall': {"image":"/media/blocks/cta-starfall-poster.webp","video":"/media/blocks/cta-starfall-preview.mp4"},
  'pricing-usage-slider': {"image":"/media/blocks/pricing-usage-slider-poster.webp","video":"/media/blocks/pricing-usage-slider-preview.mp4"},
  'grid-cascade': {"image":"/media/blocks/grid-cascade-poster.webp","video":"/media/blocks/grid-cascade-preview.mp4"},
  'cube-roll-item': {"image":"/media/blocks/cube-roll-item-poster.webp","video":"/media/blocks/cube-roll-item-preview.mp4"},
};
